feat: add resources for lesson 6 & 7 JS basics (lesson-6)
epam-nye-cooperation/epam-nye-webapp pull request #2
Opened 2022-03-25 12:17 UTC by jozsefgal

2022-03-25 23:33 UTC, veresdavid requested changes

2022-03-25 23:33 UTC, veresdavid commented on client/lesson-6/code/3a-async-timer.html
> +    <title>Example #3 - Asnych call with setTimeout</title>
Typo: `Asnych` instead of `Async`

2022-03-25 23:33 UTC, veresdavid commented on client/lesson-6/code/3b-async-timer.html
> +    <title>Example #3 - Asnych call with setTimeout</title>
Same typo here

2022-03-25 23:33 UTC, veresdavid commented on client/lesson-6/code/3c-async-timer-with-promise.html
> +    <title>Example #3 - Asnych call with setTimeout</title>
Same typo here

2022-03-27 21:33 UTC, jozsefgal commented on client/lesson-6/code/3a-async-timer.html
> +    <title>Example #3 - Asnych call with setTimeout</title>
Thanks - fixed
Copy-paste rulez :)

2022-03-27 21:48 UTC, veresdavid approved these changes

2022-03-28 22:37 UTC, merged